'use client';

import { useTranslations } from 'next-intl';
import type { TopicAggregate } from '@/lib/reviews';
import styles from './ReviewTopics.module.css';

interface Props {
  topics: TopicAggregate[];
  activeTopicKey?: string | null;
  summaryText?: string;
  onSelectTopic?: (topicKey: string | null) => void;
}

export default function ReviewTopics({
  topics,
  activeTopicKey = null,
  summaryText,
  onSelectTopic,
}: Props) {
  const t = useTranslations('reviews');
  if (topics.length === 0) return null;
  return (
    <section className={styles.box} aria-label={t('topicsAria')}>
      <h3 className={styles.title}>{t('topicsTitle')}</h3>
      {summaryText && <p className={styles.summary}>{summaryText}</p>}
      <p className={styles.label}>{t('selectAspect')}</p>
      <ul className={styles.chips}>
        <li>
          <button
            type="button"
            className={`${styles.chip} ${styles.chipAll} ${activeTopicKey === null ? styles.chipActive : ''}`}
            aria-pressed={activeTopicKey === null}
            onClick={() => onSelectTopic?.(null)}
          >
            <span className={styles.chipLabel}>{t('topicAll')}</span>
          </button>
        </li>
        {topics.map((tp) => {
          const label = t.has(`topics.${tp.key}`) ? t(`topics.${tp.key}`) : tp.key;
          return (
            <li key={tp.key}>
              <button
                type="button"
                className={`${styles.chip} ${styles[`chip-${tp.sentiment}`]} ${activeTopicKey === tp.key ? styles.chipActive : ''}`}
                aria-pressed={activeTopicKey === tp.key}
                aria-label={t('topicChipAria', { label, count: tp.count, sentiment: tp.sentiment })}
                onClick={() => onSelectTopic?.(tp.key)}
              >
                <span className={styles.chipIcon} aria-hidden="true">
                  {tp.sentiment === 'positive' ? '↗' : tp.sentiment === 'mixed' ? '~' : '↘'}
                </span>
                <span className={styles.chipLabel}>{label}</span>
                <span className={styles.chipCount}>({tp.count})</span>
              </button>
            </li>
          );
        })}
      </ul>
      <p className={styles.disclaimer}>
        {t('autoGenerated')}
      </p>
    </section>
  );
}
